spring.application.name=finance-backend
spring.jpa.show-sql=true
server.port=8080
spring.main.allow-bean-definition-overriding=true
# This is a dev-only trick; in production, you'd just close the port.